baseURL = "https://rootkey.co.uk/"
languageCode = "en-gb"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themecolor = "green"
  showMenuItems = 7
  favicon = "static/img/favicon/favicon.png"

[languages]
  [languages.en]
    title = "Rootkey"
    subtitle = "Life inside a computer"
    keywords = ""
    copyright = "Written by Ciarán Ainsworth. Theme by panr."
    menuMore = "Show More"
    readMore = "Read More"
    readOtherPosts = "Read Other Posts"

    [languages.en.params.logo]
      logoText = "Rootkey"
      logoHomeLink = "https://rootkey.co.uk/"

    [languages.en.menu]
      [[menu.main]]
        identifier = "About"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identified = "Contact"
        name = "Contact"
        url = "/contact"
      [[languages.en.menu.main]]
        identifier = "RSS"
        name = "RSS"
        url = "/index.xml"
      [[languages.en.menu.main]]
        identifier = "Support"
        name = "Support"
        url = "https://liberapay.com/CiaranAinsworth/donate"
      [[languages.en.menu.main]]
        identifier = "Blog"
        name = "Blog"
        url = "/blog/"
      [[languages.en.menu.main]]
        identifier = "Music"
        name = "Music"
        url = "/music/"
      [[languages.en.menu.main]]
        identifier = "Tech"
        name = "Tech"
        url = "/tech/"
      [[languages.en.menu.main]]
        identifier = "Resumé"
        name = "Resumé"
        url = "/resume"
