baseURL = "https://rootkey.co.uk/"
languageCode = "en-gb"
title = "Rootkey"
theme = "hello-friend"
paginate = 5
copyright  = "Written by Ciar√°n Ainsworth. Theme by panr. <a rel="me" href="https://fosstodon.org/@Sporiff">Mastodon</a>"

[params]
  subtitle = "Life Inside a Computer"

[params.logo]
  logoText = "Rootkey"

[menu]
  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about"
  [[menu.main]]
    identified = "Contact"
    name = "Contact"
    url = "/contact"
  [[menu.main]]
    identifier = "RSS"
    name = "RSS"
    url = "/index.xml"
  [[menu.main]]
    identifier = "Support"
    name = "Support"
    url = "https://liberapay.com/Rootkey/donate"
  [[menu.main]]
    identifier = "Blog"
    name = "Blog"
    url = "/post/"
