baseURL = ""
languageCode = "en-gb"
title = "Rootkey"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "Life Inside a Computer"

[params.logo]
  logoText = "Rootkey"

[menu]
  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about"
  [[menu.main]]
    identified = "Contact"
    name = "Contact"
    url = "/contact"
  [[menu.main]]
    identifier = "RSS"
    name = "RSS"
    url = "/index.xml"
  [[menu.main]]
    identifier = "Blog"
    name = "Blog"
    url = "/post/"
